config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  get "up" => "rails/health#show", :as => :rails_health_check

  root "pages#home"

  resources :email_files, only: [:new, :create, :index] do
    collection do
      get  "/upload", to: "email_files#upload", as: :upload_emails
      post "/upload", to: "email_files#process_file", as: :process_emails
    end
  end

  resources :customers, only: [:index, :show]
  resources :processing_logs, only: [:index, :show]

  # API namespace (mantido vazio por enquanto)
  namespace :api do
  end

  mount ActionCable.server => "/cable"
end

app/views/shared/_navbar.html.erb
<nav class="navbar bg-neutral shadow-lg text-white">
  <div class="flex-1">
    <a class="btn btn-ghost text-xl" href="/">EML Processor</a>
  </div>

  <div class="navbar-end">
    <div class="mx-2">
      <%= link_to "Customers", customers_path, class: "nav-link" %>
    </div>

    <div class="mx-2">
      <%= link_to "Logs", processing_logs_path, class: "nav-link" %>
    </div>
  </div>
</nav>

app/views/shared/_notification_card.html.erb
<turbo-frame id="notification_card" data-turbo-permanent>
  <div data-controller="notification" data-notification-target="card" class="fixed z-50 hidden top-24 right-5 max-w-md w-full">
    <div data-controller="draggable" class="card bg-base-100 shadow-2xl w-96 border">
      <div class="card-body">
        <h2 class="text-primary text-center text-xl">Processando...</h2>

        <div class="flex my-3 items-center">
          <span class="loading loading-spinner text-primary h-8 w-8" data-notification-target="waiting"></span>
          <span class="material-symbols-outlined text-red-600 text-4xl hidden" data-notification-target="error">dangerous</span>
          <span class="material-symbols-outlined text-success text-4xl hidden" data-notification-target="success">check_circle</span>

          <span class="mx-2 text-center text-lg" data-notification-target="message"></span>
        </div>

        <hr data-notification-target="line" class="absolute left-0 right-0 bottom-20 hidden">

        <div class="flex justify-center gap-5 mt-7">
            <%= link_to "Customers", customers_path,
              data: { "notification-target": "customersButton", "turbo-frame": "_top" },
              class: "btn btn-sm w-24 btn-primary text-white hidden"
            %>

            <%= link_to "Logs", processing_logs_path,
              data: { "notification-target": "logsButton", "turbo-frame": "_top" },
              class: "btn btn-sm w-16 btn-primary text-white hidden"
            %>

          <button data-action="click->notification#close" data-notification-target="closeButton" class="btn btn-sm w-16 btn-error text-white hidden">
            Fechar
          </button>
        </div>
      </div>
    </div>
  </div>
</turbo-frame>

app/views/shared/_patient_foot.html.erb
<tfoot>
  <thead>
    <tr>
      <th colspan="5" class="font-semibold text-base pt-7">Quantidade</th>
      <th class="font-semibold text-base pt-7">Valor Disponível</th>
    </tr>
  </thead>

  <tbody>
    <tr class="bg-gray-200 border-t border-b border-black h-10">
      <td colspan="5"><%= monthly_report.quantity %></td>
      <td><%= number_to_currency(monthly_report.available_value) %></td>
    </tr>
  </tbody>
</tfoot>

app/views/shared/_patient_header.html.erb
<div class="overflow-hidden">
  <table class="table-auto w-full">
    <thead class="text-base text-left">
      <tr>
        <th class="text-primary"><%= representative.name.upcase %></th>

        <th class="flex gap-16">
          <span>
            Fechamento: <span class="text-primary"><%= closing %></span>
          </span>

          <span>
            Situação:
            <span class="text-primary"><%= monthly_report.situation %></span>
          </span>

          <span>
            Número do Envelope:
            <span class="text-primary">
              <%= monthly_report.envelope_number.to_s.rjust(5, '0') %>
            </span>
          </span>
        </th>
      </tr>
    </thead>
  </table>
</div>