config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  get "up" => "rails/health#show", :as => :rails_health_check

  root "pages#home"

  resources :email_files, only: [:new, :create, :index] do
    collection do
      get  "/upload", to: "email_files#upload", as: :upload_emails
      post "/upload", to: "email_files#process_file", as: :process_emails
    end
  end

  resources :customers, only: [:index, :show]
  resources :processing_logs, only: [:index, :show]

  # API namespace (mantido vazio por enquanto)
  namespace :api do
  end

  mount ActionCable.server => "/cable"
end

app/views/pages/home.html.erb
<div class="flex items-center justify-center bg-base-200 my-10">
  <div class="card shadow-2xl bg-base-100">
    <div class="card-body items-center text-center">
      <h1 class="card-title text-4xl font-bold">
        Processador de E-mails (.eml)
      </h1>

      <p class="text-lg text-base-content/80 mt-2">
        Envie arquivos .eml e veja os clientes extraídos e os logs de processamento.
      </p>

      <div class="divider mt-4"></div>

      <%= form_with url: upload_emails_email_files_path, multipart: true, local: true, class: "w-full max-w-lg space-y-6", method: :post do |f| %>
        <div class="form-control border rounded-lg p-2">
          <label class="label">
            <span class="label-text font-semibold text-base">Selecione arquivos .eml</span>
          </label>

          <%= f.file_field :files, multiple: true, accept: ".eml",
              class: "file-input file-input-bordered file-input-lg w-full bg-gray-200"
          %>
        </div>

        <div class="flex justify-center">
          <%= f.submit "Enviar e Processar", class: "btn btn-primary btn-lg px-10 shadow-lg" %>
        </div>
      <% end %>

      <div class="divider mt-6"></div>

      <p class="text-sm text-base-content/60">
        Arquivos permitidos: <span class="font-semibold">.eml</span>
      </p>
    </div>
  </div>
</div>